Repository popcornToy/naramRemodeling, pull requests merged in 2024-04, with the labels that each got.

#1 [feature] routes 주소연결, Login,Main,Instroduction 페이지 간단 연결 태욱
  src/App.tsx
  src/components/layouts/RootLayout.tsx
  src/pages/Introduction.tsx
  src/pages/Login.tsx
  src/pages/main.tsx
  src/routes/index.tsx
  src/routes/navigation.tsx
Labels: feature

#5 [Init] reset file 추가
  src/main.tsx
  src/styles/GlobalStyles.ts
Labels: feature

#7 [feat] atom pageTitle구현 및dropDown 구현중
  package-lock.json
  public/svg/dropdown.svg
  src/components/atoms/Board/DropDown.tsx
  src/components/atoms/Board/ShowTotalBoard.tsx
  src/components/atoms/PageTitle/PageTitle.tsx
  src/pages/Board.tsx
  src/pages/QnA.tsx
  src/routes/navigation.tsx
  src/styles/components/Board.ts
Labels: feature

#8 [feat] DropDown, SearchBar 컴포넌트 구현중
  public/dropdown.svg
  public/search.svg
  src/components/atoms/Board/DropDown.tsx
  src/components/atoms/Board/SearchBar.tsx
  src/components/atoms/Board/ShowTotalBoard.tsx
  src/components/atoms/PageTitle/PageTitle.tsx
  src/components/moleclues/BoardTable/BoardTable.tsx
  src/components/moleclues/Search/Search.tsx
  src/pages/Board.tsx
  src/styles/components/Board.ts
  src/styles/components/Board/Board.ts
  src/styles/components/Board/StyledDropDown.ts
Labels: feature

#9 [Feat] PageTitle, PageMainMenu 합치기 헤더 + 푸터 컴포넌트 만들기 전 태욱
  src/components/atoms/PageMainImage/PageMainImage.tsx
  src/components/moleclues/MainMenuButton/MainMenuButton.stories.tsx
  src/components/moleclues/MainMenuButton/MainMenuButton.tsx
  src/pages/Introduction/Introduction.tsx
  src/styles/components/Board/Board.ts
  src/styles/components/IntroductionPage/Introduction.ts
  src/styles/components/MainMenuButton/MainMenuButton.ts
  src/styles/components/PageMainImage/PageMainImage.ts
  src/styles/components/PageMainImageWrapper/PageMainImageWrapper.ts
Labels: feature

#11 [feat] 게시판 컴포넌트 구현 완료
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/atoms/Board/BasicButton.tsx
  src/components/atoms/Board/Pagination.tsx
  src/components/atoms/Board/ShowTotalBoard.tsx
  src/components/moleclues/BoardTable/BoardTable.tsx
  src/components/organisms/BoardLayout/BoardLayout.tsx
  src/pages/CustomerService/CustomerService.tsx
  src/pages/Notice/Notice.tsx
  src/pages/QnA/QnA.tsx
  src/routes/navigation.tsx
  src/styles/components/Board/Board.ts
  src/styles/components/Board/DropDown.ts
Labels: feature

#12 [Modify] PageLayout 수정 태욱 route 구성
  src/components/moleclues/MainMenuButton/MainMenuButton.tsx
  src/components/moleclues/PageSubTitleLayout/PageSubTitleLayout.tsx
  src/components/moleclues/naviButton/NaviBar.tsx
  src/components/organisms/PageLayout/PageLayout.tsx
  src/pages/CompanyIntroduction/CompanyIntroduction.stories.tsx
  src/pages/CompanyIntroduction/CompanyIntroduction.tsx
  src/pages/CompanyIntroduction/SubPage/Instroduction.tsx
  src/pages/CompanyIntroduction/SubPage/Location.tsx
  src/pages/Introduction/CompanyIntroduction.tsx
  src/pages/Introduction/components/IntroductionContent.tsx
  src/pages/Introduction/components/LocationContent.tsx
  src/pages/Introduction/components/introductionContent.stories.tsx
  src/pages/Introduction/pages/Introduction.tsx
  src/pages/Introduction/pages/Location.tsx
  src/routes/navigation.tsx
  src/styles/components/IntroductionPage/Introduction.ts
Labels: feature, modify

#13 [Feat] 네비게이션 컴포넌트 속성 추가 및 메인페이지 작업
  .github/pull_request_template.md
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  pnpm-lock.yaml
  public/mainBanner.png
  src/components/atoms/naviButton/NaviButton.tsx
  src/components/moleclues/naviButton/NaviBar.stories.tsx
  src/components/moleclues/naviButton/NaviBar.tsx
  src/pages/Main/Main.tsx
  src/pages/main.tsx
  src/routes/navigation.tsx
  src/styles/GlobalStyles.ts
  src/styles/components/MainPage/MainPage.ts
  src/styles/components/naviButton/naviButton.ts
  src/styles/index.ts
Labels: feature

#14 [Design] 네비게이션 디자인 변경
  src/components/atoms/naviButton/NaviButton.tsx
  src/components/moleclues/naviButton/NaviBar.stories.tsx
  src/components/moleclues/naviButton/NaviBar.tsx
  src/components/organisms/PageLayout/PageLayout.tsx
  src/pages/Main/Main.tsx
  src/styles/components/MainPage/MainPage.ts
  src/styles/components/naviButton/naviButton.ts
Labels: feature, modify

#15 [Feat] 로그인 / 로그아웃 버튼 추가
  public/logout.svg
  public/user.svg
  src/components/atoms/naviButton/NaviButton.tsx
  src/components/moleclues/naviButton/NaviBar.stories.tsx
  src/components/moleclues/naviButton/NaviBar.tsx
  src/components/moleclues/naviButton/legacy/NaviBar.tsx
  src/pages/MyPage/MyPage.tsx
  src/routes/navigation.tsx
  src/styles/components/naviButton/naviButton.ts
Labels: feature, modify

#18 [Feat] 스크롤 시 네비게이션 색상 변경
  package.json
  pnpm-lock.yaml
  public/logout.svg
  public/user.svg
  src/components/atoms/naviButton/NaviButton.stories.tsx
  src/components/atoms/naviButton/NaviButton.tsx
  src/components/moleclues/MainMenuButton/MainMenuButton.stories.tsx
  src/components/moleclues/MainMenuButton/MainMenuButton.tsx
  src/components/moleclues/naviButton/NaviBar.stories.tsx
  src/components/moleclues/naviButton/NaviBar.tsx
  src/components/organisms/Header/Header.stories.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/PageLayout/PageLayout.tsx
  src/pages/Main/Main.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/components/Header/Header.ts
  src/styles/components/naviButton/naviButton.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: feature, modify

#20 [Feat] Footer 컴포넌트, storybook 추가,AddressIcon, AddressGrop 컴포넌트 등 태욱
  index.html
  public/address_icon.svg
  public/email_icon.svg
  public/fex_icon.svg
  public/logo_mark.svg
  public/phonNumber_icon.svg
  src/components/atoms/AddressIcon/AddressIcon.stories.tsx
  src/components/atoms/AddressIcon/AddressIcon.tsx
  src/components/atoms/Footer/Footer.stories.tsx
  src/components/atoms/Footer/Footer.tsx
  src/components/atoms/KakaoMap/KakaoMap.stories.tsx
  src/components/atoms/KakaoMap/KakaoMap.tsx
  src/components/atoms/PageTitle/PageSubTitle.tsx
  src/components/moleclues/AddressGrop/AddressGrop.stories.tsx
  src/components/moleclues/AddressGrop/AddressGrop.tsx
  src/components/moleclues/PageSubTitleLayout/PageSubTitleLayout.stories.tsx
  src/components/moleclues/PageSubTitleLayout/PageSubTitleLayout.tsx
  src/components/organisms/PageLayout/PageLayout.stories.tsx
  src/components/organisms/PageLayout/PageLayout.tsx
  src/pages/CompanyIntroduction/components/LocationContent.tsx
  src/pages/CompanyIntroduction/components/introductionContent.stories.tsx
  src/pages/CompanyIntroduction/pages/Introduction.tsx
  src/pages/CompanyIntroduction/pages/Location.tsx
  src/styles/components/AddressGroup/AddressGroup.ts
  src/styles/components/Footer/Footer.tsx
  src/styles/components/IntroductionPage/Introduction.ts
  src/styles/components/KakaoMap/KakaoMap.ts
  src/styles/components/Location/Location.ts
  src/styles/components/PageSubTitle/PageSubTitle.ts
Labels: feature

#21 [Design] GNB에 드롭다운메뉴 적용중
  package.json
  pnpm-lock.yaml
  public/letter_icon.svg
  src/components/atoms/Dropdown/DropdownContents.stories.tsx
  src/components/atoms/Dropdown/DropdownContents.tsx
  src/components/atoms/Dropdown/DropdownTitle.stories.ts
  src/components/atoms/Dropdown/DropdownTitle.tsx
  src/components/atoms/LogoLink/LogoLink.tsx
  src/components/atoms/naviButton/NaviButton.tsx
  src/components/moleclues/Dropdown/DropdownMenu.stories.tsx
  src/components/moleclues/Dropdown/DropdownMenu.tsx
  src/components/moleclues/naviButton/NaviBar.tsx
  src/components/organisms/Dropdown/DropdownMenuNav.stories.tsx
  src/components/organisms/Dropdown/DropdownMenuNav.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Header/useBackground.ts
  src/pages/Main/Main.tsx
  src/store/store.ts
  src/styles/GlobalStyles.ts
  src/styles/components/DropdownMenu/Dropdown.ts
  src/styles/components/Header/Header.ts
  src/styles/components/naviButton/naviButton.ts
Labels: feature

#22 [Feat] GNB 메뉴 조건 추가
  src/components/atoms/Dropdown/DropdownContents.tsx
  src/components/atoms/LogoLink/LogoLink.tsx
  src/components/atoms/naviButton/NaviButton.tsx
  src/components/organisms/Dropdown/DropdownMenuNav.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/Header/useBackground.ts
  src/store/store.ts
  src/styles/components/DropdownMenu/Dropdown.ts
  src/styles/components/naviButton/naviButton.ts
Labels: bug, feature

#23 [feat] 페이지네이션 UI 구현 완료
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/atoms/Board/Pagination.tsx
  src/components/moleclues/BoardTable/BoardTable.tsx
  src/styles/components/Board/Pagination.ts
Labels: feature

#24 [Feat] PageLayout 수정, Footer 컴포넌트 위치, 로그인페이지, 아이디찾기, 비밀번호찾기 페이지 구성 태욱
  src/components/atoms/Form/Form.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/Login/Button.tsx
  src/components/organisms/PageLayout/PageLayout.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/components/LoginForm.tsx
  src/pages/Login/pages/FindId.tsx
  src/pages/Login/pages/FindPassword.tsx
  src/pages/Login/pages/Login.tsx
  src/pages/SearchId/SearchId.tsx
  src/pages/SearchPassword/SearchPassword.tsx
  src/routes/navigation.tsx
  src/styles/components/IntroductionPage/Introduction.ts
  src/styles/components/Login/Button.ts
Labels: feature

#25 [feat] board 컴포넌트 pagination 기능 구현
  src/components/atoms/Board/Pagination.tsx
  src/components/moleclues/BoardTable/BoardTable.tsx
  src/components/moleclues/PaginationBar/PaginationBar.tsx
  src/components/organisms/BoardLayout/BoardLayout.tsx
  src/styles/components/Board/Board.ts
  src/styles/components/Board/Pagination.ts
Labels: feature

#27 [Modify] RootLayout 에 Header Footer 컴포넌트 추가, 지인님 Notice 페이지 수정 태욱
  src/components/atoms/Input/Input.tsx
  src/components/layouts/RootLayout.tsx
  src/components/organisms/BoardLayout/BoardLayout.tsx
  src/components/organisms/Dropdown/DropdownMenuNav.tsx
  src/components/organisms/PageLayout/PageLayout.tsx
  src/pages/CompanyIntroduction/components/IntroductionContent.tsx
  src/pages/Login/components/LoginForm.tsx
  src/styles/components/Login/LoginForm.ts
Labels: modify

#28 Board detail
  package-lock.json
  package.json
  src/components/moleclues/Editor/Editor.tsx
  src/components/organisms/Dropdown/DropdownMenuNav.tsx
  src/pages/Main/Main.tsx
  src/pages/Notice/Information.tsx
  src/pages/Notice/pages/Notice.tsx
  src/pages/Notice/pages/Promotion.tsx
  src/routes/navigation.tsx
  src/styles/components/Board/Board.ts
  src/styles/components/PageSubTitle/PageSubTitle.ts
Labels: modify

#30 [feat] 게시판 페이지 컴포넌트 구현중
  src/components/atoms/Board/BasicButton.tsx
  src/components/atoms/PageTitle/PageSubTitle.tsx
  src/components/moleclues/BoardTable/BoardTable.tsx
  src/components/moleclues/Editor/Editor.tsx
  src/components/moleclues/PageSubTitleLayout/PageSubTitleLayout.tsx
  src/components/organisms/PageLayout/PageLayout.tsx
  src/components/organisms/PageLayout/WritePageLayout.tsx
  src/pages/NoticeDetail/WritePage.tsx
  src/routes/navigation.tsx
  src/styles/components/Editor/Editor.ts
  src/styles/components/IntroductionPage/Introduction.ts
Labels: feature

#29 [Feat] 로그인UI 구성 태욱
  public/danger-circle.svg
  public/find_password.svg
  public/find_user.svg
  public/hide.svg
  public/nothide.svg
  src/components/atoms/Form/Form.tsx
  src/components/atoms/Input/Input.tsx
  src/components/atoms/Input/LoginInput.stories.tsx
  src/components/atoms/Input/LoginInput.tsx
  src/components/atoms/Login/Button.tsx
  src/components/organisms/Dropdown/DropdownMenuNav.tsx
  src/main.tsx
  src/pages/CompanyIntroduction/components/IntroductionContent.tsx
  src/pages/Login/components/LoginForm.tsx
  src/pages/Login/pages/Login.tsx
  src/styles/GlobalStyles.ts
  src/styles/components/Login/Button.ts
  src/styles/components/Login/LoginForm.ts
Labels: feature

#31 [Feat] GNB 및 제품정보 사이드메뉴
  public/productPage.png
  src/components/atoms/ProductMenu/ProductTitle.stories.tsx
  src/components/atoms/ProductMenu/ProductTitle.tsx
  src/components/atoms/naviButton/NaviButton.tsx
  src/components/moleclues/ProductMenu/ProductCollection.stories.tsx
  src/components/moleclues/ProductMenu/ProductCollection.tsx
  src/components/organisms/Dropdown/DropdownMenuNav.tsx
  src/components/organisms/Header/Header.tsx
  src/pages/CompanyIntroduction/components/IntroductionContent.tsx
  src/pages/Main/Main.tsx
  src/pages/ProductInformation/ProductInformation.tsx
  src/routes/navigation.tsx
  src/styles/GlobalStyles.ts
  src/styles/components/MainPage/MainPage.ts
  src/styles/components/Product/Product.ts
Labels: feature

#32 인재채용, 문의하기 페이지 연결 및 컴포넌트 props 수정
  src/components/atoms/Board/BasicButton.tsx
  src/components/atoms/Board/BasicFormButton.tsx
  src/components/moleclues/BoardTable/BoardTable.tsx
  src/components/moleclues/Editor/ Editor.tsx
  src/components/moleclues/EditorInput/EditorInputContainer.tsx
  src/components/moleclues/FormButton/FormButton.tsx
  src/components/organisms/BoardLayout/BoardLayout.tsx
  src/components/organisms/Dropdown/DropdownMenuNav.tsx
  src/pages/Notice/pages/Notice.tsx
  src/pages/QnA/QnA.tsx
  src/pages/Recruitment/Recruitment.tsx
  src/pages/Write/NoticeWritePage.tsx
  src/pages/Write/QnAWritePage.tsx
  src/pages/Write/RecruitmentPage.tsx
  src/pages/Write/WritePage.tsx
  src/routes/navigation.tsx
  src/styles/components/Board/Board.ts
  src/styles/components/Editor/Editor.ts
Labels: feature

#34 [feat] 홍보게시물 UI 구현 및 글쓰기 페이지 연동 완료
  public/Promotion.svg
  src/components/atoms/PromotionImage/PromotionContainer.tsx
  src/components/moleclues/PromotionList/PromotionList.tsx
  src/components/organisms/Dropdown/DropdownMenuNav.tsx
  src/components/organisms/PromotionLayout/PromotionLayout.tsx
  src/pages/Notice/pages/Promotion.tsx
  src/pages/Write/PromotionWrite.tsx
  src/pages/Write/WritePage.tsx
  src/routes/navigation.tsx
  src/styles/Promotion/Promotion.ts
  src/styles/components/Board/Board.ts
  src/styles/components/IntroductionPage/Introduction.ts
Labels: feature

#39 Detail
  .eslintrc.cjs
  public/checkboxAfter.svg
  public/checkboxBefore.svg
  src/components/atoms/CheckBox/CheckBox.tsx
  src/components/atoms/PasswordInput/PasswordInput.tsx
  src/components/moleclues/Editor/Editor.tsx
  src/components/moleclues/EditorInput/EditorInputContainer.tsx
  src/components/moleclues/FormButton/FormButton.tsx
  src/components/moleclues/NormalCheckBox/NormalCheckBox.tsx
  src/components/moleclues/QnACheckBox/QnACheckBox.tsx
  src/pages/QnA.tsx
  src/pages/Write/NoticeWritePage.tsx
  src/pages/Write/PromotionWrite.tsx
  src/pages/Write/QnAWritePage.tsx
  src/pages/Write/RecruitmentPage.tsx
  src/styles/components/Board/Board.ts
  src/styles/components/Editor/Editor.ts
Labels: feature

#40 [Feat] theme 적용 및 회원가입 input 작성
  src/components/atoms/Input/JoinInput.tsx
  src/components/atoms/JoinButton/JoinButton.tsx
  src/components/atoms/JoinSubTitle/JoinSubTitle.tsx
  src/components/moleclues/JoinInputWrap/JoinInputWrap.tsx
  src/main.tsx
  src/pages/Join/Join.tsx
  src/store/store.ts
  src/styles/theme.ts
Labels: feature
